name: Lint workflows
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
