name: Check

on:
  workflow_call:
    inputs:
      features:
        type: string
        required: false
        default: "async,tokio-support"
      compare-branch:
        type: string
        required: false
        default: main

jobs:
  read-toolchain:
    uses: ShuttlePub/workflows/.github/workflows/read-toolchain.yml@main
  detect-workspaces:
    uses: ShuttlePub/workflows/.github/workflows/detect-workspaces.yml@main
    
  check:
    needs: [read-toolchain, detect-workspaces]
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          workspace: ${{ fromJson(needs.detect-workspaces.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ needs.read-toolchain.outputs.channel }}
      - name: Bench
        uses: boa-dev/criterion-compare-action@v3
        with:
          branchName: ${{ inputs.compare-branch }}
          package: ${{ matrix.workspace }}
          features: ${{ inputs.features }}
