name: Check

on:
  workflow_call:

jobs:
  read-toolchain:
    uses: ShuttlePub/workflows/.github/workflows/read-toolchain.yml@main
  detect-workspaces:
    uses: ShuttlePub/workflows/.github/workflows/detect-workspaces.yml@main

  check:
    needs: [read-toolchain, detect-workspaces]
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          workspace: ${{ fromJson(needs.detect-workspaces.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ needs.read-toolchain.outputs.channel }}
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.workspace }}
      - name: Format check
        run: cargo fmt --verbose -p ${{ matrix.workspace }} -- --check
      - uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          clippy_flags: '-p ${{ matrix.workspace }} -- -Dwarnings'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: cargo build --verbose -p ${{ matrix.workspace }}
      - name: Test
        run: cargo test --verbose -p ${{ matrix.workspace }}
