name: Check

on:
  workflow_call:
    inputs:
      channel:
        type: string
        required: false
        default: stable
      gen_coverage:
        type: boolean
        required: false
        default: false

jobs:
  detect-workspaces:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'ShuttlePub' && !contains(github.event.head_commit.message, '[CI-SKIP]') }}
    steps:
      - uses: actions/checkout@v3
      - uses: brndnmtthws/rust-action-cargo-binstall@v1
        with:
          packages: cargo-workspaces
      - run: cargo install cargo-workspaces
      - id: set-matrix
        run: |
          # outputs like ["kernel","driver"]
          WORKSPACES=$(echo "[$(cargo ws ls)]" | tr '\n' ',\t' | sed -e 's/],/\"]\n/' | sed -e 's/\[/\[\"/' | sed -e 's/,/\",\"/g')
          echo "result: $WORKSPACES"
          echo "matrix=$WORKSPACES" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    
  check:
    needs: detect-workspaces
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          workspace: ${{ fromJson(needs.detect-workspaces.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.channel }}
          components: clippy
      - if: ${{ inputs.gen_coverage }}
        uses: taiki-e/install-action@cargo-llvm-cov
      - uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          clippy_flags: '-p ${{ matrix.workspace }} -- -Dwarnings'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: cargo build --verbose -p ${{ matrix.workspace }}
      - name: Test
        run: |
          if [ ${{ inputs.gen_coverage }} = true ]; then
            cargo llvm-cov --codecov --verbose -p ${{ matrix.workspace }} --output-path coverage-${{ matrix.workspace }}.json
          else
            cargo test --verbose -p ${{ matrix.workspace }}
          fi
