name: Read rust-toolchain.toml

on:
  workflow_call:
    outputs:
      channel:
        description: "Detected toolchain channel"
        value: ${{ jobs.read-toolchain.outputs.channel }}
    
jobs:
  read-toolchain:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'ShuttlePub' && !contains(github.event.head_commit.message, '[CI-SKIP]') }}
    steps:
      - uses: actions/checkout@v4
      - uses: SebRollen/toml-action@v1.2.0
        id: toolchain
        with:
          file: "rust-toolchain.toml"
          field: "toolchain.channel"
      - run: |
          echo "detected: ${{ steps.toolchain.outputs.value }}"
    outputs:
      channel: ${{ steps.toolchain.outputs.value }}
